# -*- coding: utf-8 -*-

# General information about the project.
project = u'The DevOps Pipeline'
copyright = u'Copyright © 2020 by Franklin Diaz'
author = u'© 2020 by Franklin Diaz'

# The short X.Y version
version = '0.0.2'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.intersphinx',
    'sphinx.ext.graphviz',
    'rst2pdf.pdfbuilder']

# Turns on numbered figures for HTML output
numfig = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'colorful'


# -- Options for HTML output -------------------------------------------------
# The Read the Docs theme is available from
# - https://github.com/snide/sphinx_rtd_theme
# - https://pypi.python.org/pypi/sphinx_rtd_theme
# - python-sphinx-rtd-theme package (on Debian)
try:
    #import sphinx_rtd_theme
    #html_theme = 'sphinx_rtd_theme'
    #html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
    html_theme = 'theme' # use the theme in subdir 'theme'
    html_theme_path = ['.'] # make sphinx search for themes in current dir
except ImportError:
    sys.stderr.write('Warning: The Sphinx custom HTML theme was not found. Falling back to the default theme.\n')
    #sys.stderr.write('Warning: The Sphinx \'sphinx_rtd_theme\' HTML theme was not found. Make sure you have the theme installed to produce pretty HTML output. Falling back to the default theme.\n')

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # Disable showing the sidebar. Defaults to 'false'
    'nosidebar': True
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['theme/static']
html_context = {
    'css_files': [
        'theme/static/colorful.css',
    ],
}

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
html_sidebars = {}

html_use_index = False
html_show_sphinx = False
html_domain_indices = False

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '10pt'

latex_show_pagerefs = True
latex_show_urls = 'footnote'
latex_additional_files = ['sphinxmanual.cls'] 

latex_elements = {
    'inputenc': '',
    'utf8extra': '',
    'papersize':'letterpaper',
}