
\begin{tikzpicture}[>=latex,line join=bevel,]
  \pgfsetlinewidth{1bp}
%%
\pgfsetcolor{black}
  % Edge: devsecops -> python
  \draw [->] (167.95bp,143.88bp) .. controls (150.51bp,134.55bp) and (128.73bp,122.92bp)  .. (101.17bp,108.19bp);
  % Edge: devsecops -> docker
  \draw [->] (188.38bp,143.7bp) .. controls (182.86bp,135.47bp) and (176.15bp,125.48bp)  .. (164.48bp,108.1bp);
  % Edge: devsecops -> terraform
  \draw [->] (211.62bp,143.7bp) .. controls (217.14bp,135.47bp) and (223.85bp,125.48bp)  .. (235.52bp,108.1bp);
  % Edge: devsecops -> Makefile
  \draw [->] (235.96bp,143.88bp) .. controls (255.88bp,134.39bp) and (280.82bp,122.51bp)  .. (311.16bp,108.07bp);
  % Edge: docker -> comp
  \draw [->] (135.2bp,71.697bp) .. controls (126.4bp,63.135bp) and (115.62bp,52.656bp)  .. (98.593bp,36.104bp);
  % Edge: docker -> Dockerfile
  \draw [->] (170.8bp,71.697bp) .. controls (179.6bp,63.135bp) and (190.38bp,52.656bp)  .. (207.41bp,36.104bp);
  % Node: devsecops
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (245.0bp,180.0bp) -- (242.0bp,184.0bp) -- (221.0bp,184.0bp) -- (218.0bp,180.0bp) -- (155.0bp,180.0bp) -- (155.0bp,144.0bp) -- (245.0bp,144.0bp) -- cycle;
  \draw (200.0bp,162.0bp) node {devsecops};
\end{scope}
  % Node: python
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (102.0bp,108.0bp) -- (99.0bp,112.0bp) -- (78.0bp,112.0bp) -- (75.0bp,108.0bp) -- (36.0bp,108.0bp) -- (36.0bp,72.0bp) -- (102.0bp,72.0bp) -- cycle;
  \draw (69.0bp,90.0bp) node {python};
\end{scope}
  % Node: docker
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (185.5bp,108.0bp) -- (182.5bp,112.0bp) -- (161.5bp,112.0bp) -- (158.5bp,108.0bp) -- (120.5bp,108.0bp) -- (120.5bp,72.0bp) -- (185.5bp,72.0bp) -- cycle;
  \draw (153.0bp,90.0bp) node {docker};
\end{scope}
  % Node: terraform
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (290.0bp,108.0bp) -- (287.0bp,112.0bp) -- (266.0bp,112.0bp) -- (263.0bp,108.0bp) -- (204.0bp,108.0bp) -- (204.0bp,72.0bp) -- (290.0bp,72.0bp) -- cycle;
  \draw (247.0bp,90.0bp) node {terraform};
\end{scope}
  % Node: Makefile
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (385.5bp,108.0bp) -- (308.5bp,108.0bp) -- (308.5bp,72.0bp) -- (385.5bp,72.0bp) -- cycle;
  \draw (347.0bp,90.0bp) node {Makefile};
\end{scope}
  % Node: comp
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (162.0bp,36.0bp) -- (0.0bp,36.0bp) -- (0.0bp,0.0bp) -- (162.0bp,0.0bp) -- cycle;
  \draw (81.0bp,18.0bp) node {docker-compose.yml};
\end{scope}
  % Node: Dockerfile
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (269.5bp,36.0bp) -- (180.5bp,36.0bp) -- (180.5bp,0.0bp) -- (269.5bp,0.0bp) -- cycle;
  \draw (225.0bp,18.0bp) node {Dockerfile};
\end{scope}
%
\end{tikzpicture}

