
\begin{tikzpicture}[>=latex,line join=bevel,]
  \pgfsetlinewidth{1bp}
%%
\pgfsetcolor{black}
  % Edge: devsecops -> python
  \draw [->] (137.99bp,143.83bp) .. controls (123.71bp,134.57bp) and (106.18bp,123.2bp)  .. (82.234bp,107.67bp);
  % Edge: devsecops -> docker
  \draw [->] (156.16bp,143.83bp) .. controls (151.8bp,135.79bp) and (146.59bp,126.17bp)  .. (136.97bp,108.41bp);
  % Edge: devsecops -> terraform
  \draw [->] (176.09bp,143.83bp) .. controls (180.56bp,135.79bp) and (185.91bp,126.17bp)  .. (195.77bp,108.41bp);
  % Edge: devsecops -> Makefile
  \draw [->] (197.54bp,143.83bp) .. controls (213.68bp,134.54bp) and (233.5bp,123.12bp)  .. (259.47bp,108.16bp);
  % Edge: docker -> comp
  \draw [->] (111.61bp,71.831bp) .. controls (104.51bp,63.454bp) and (95.952bp,53.353bp)  .. (81.6bp,36.413bp);
  % Edge: docker -> Dockerfile
  \draw [->] (142.14bp,71.831bp) .. controls (149.12bp,63.454bp) and (157.54bp,53.353bp)  .. (171.66bp,36.413bp);
  % Node: devsecops
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (202.0bp,180.0bp) -- (199.0bp,184.0bp) -- (178.0bp,184.0bp) -- (175.0bp,180.0bp) -- (130.0bp,180.0bp) -- (130.0bp,144.0bp) -- (202.0bp,144.0bp) -- cycle;
  \draw (166.0bp,162.0bp) node {devsecops};
\end{scope}
  % Node: python
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (82.0bp,108.0bp) -- (79.0bp,112.0bp) -- (58.0bp,112.0bp) -- (55.0bp,108.0bp) -- (28.0bp,108.0bp) -- (28.0bp,72.0bp) -- (82.0bp,72.0bp) -- cycle;
  \draw (55.0bp,90.0bp) node {python};
\end{scope}
  % Node: docker
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (154.0bp,108.0bp) -- (151.0bp,112.0bp) -- (130.0bp,112.0bp) -- (127.0bp,108.0bp) -- (100.0bp,108.0bp) -- (100.0bp,72.0bp) -- (154.0bp,72.0bp) -- cycle;
  \draw (127.0bp,90.0bp) node {docker};
\end{scope}
  % Node: terraform
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (240.0bp,108.0bp) -- (237.0bp,112.0bp) -- (216.0bp,112.0bp) -- (213.0bp,108.0bp) -- (172.0bp,108.0bp) -- (172.0bp,72.0bp) -- (240.0bp,72.0bp) -- cycle;
  \draw (206.0bp,90.0bp) node {terraform};
\end{scope}
  % Node: Makefile
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (324.0bp,108.0bp) -- (258.0bp,108.0bp) -- (258.0bp,72.0bp) -- (324.0bp,72.0bp) -- cycle;
  \draw (291.0bp,90.0bp) node {Makefile};
\end{scope}
  % Node: comp
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (132.0bp,36.0bp) -- (0.0bp,36.0bp) -- (0.0bp,0.0bp) -- (132.0bp,0.0bp) -- cycle;
  \draw (66.0bp,18.0bp) node {docker-compose.yml};
\end{scope}
  % Node: Dockerfile
\begin{scope}
  \definecolor{strokecol}{rgb}{0.0,0.0,0.0};
  \pgfsetstrokecolor{strokecol}
  \draw (224.0bp,36.0bp) -- (150.0bp,36.0bp) -- (150.0bp,0.0bp) -- (224.0bp,0.0bp) -- cycle;
  \draw (187.0bp,18.0bp) node {Dockerfile};
\end{scope}
%
\end{tikzpicture}

