\newcommand{\sphinxbackoftitlepage}{%
\vspace*{\fill}
\begingroup
\centering
© 2019 Nicholas Touran, All Rights Reserved
\\~\\
\url{https://digitalsuperpowers.com}
\\~\\
Icons on cover are from FontAwesome, used under a CC BY 4.0 License available at
\url{https://fontawesome.com/license/free}. Modifications to the laptop icon were 
made.
\\~\\
Revision: $release
\\~\\
Published on: $date

\endgroup
\vspace*{\fill}
\clearpage
}
